AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Fx Lambda Node Demo
Resources:
  FxLambdaNodeDemo:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: FxLambdaNodeDemo
      Handler: index.handler
      Runtime: nodejs10.x
      CodeUri: ./LambdaCode
      Description: 'Lambda function Node Demo'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::771861526154:role/MyLambdaRole'
      Events:
        getAZsAPI:
          Type: Api
          Properties:
            Path: /users
            Method: get
      Environment:
        Variables:
          REGION: us-east-1